### ISSUE TITLE
Other Providers For Contacts

### ISSUE THREAD

**Issue by cwmke** [andyholmes/gnome-shell-extension-mconnect#16]
Any chance of adding other GOA service's contacts? For example, Nextcloud is my current contact service. Thanks for the very useful extension and any consideration for this idea.

**Comment by andyholmes** [comment]
It's possible, I'm sure. At the moment GOA is only used for authentication with Google (eg. it doesn't even matter if Contacts is enable in Google GOA account) all contact data is retrieved via GData because it was the quickest, easiest way to get contacts.

As I understand it, that's really what GOA is for, whereas actually retrieving data from the providers requires implementing the specific REST API for the given provider. This is something I have no experience with and would probably result in ginormous amounts of code (and sms.js is already larger than extension.js as it is).

Ideally the extension would interface with Gnome Contacts which aggregates and processes a bunch of sources (libfolks, telepathy, Evolution, etc), but this appears to not be currently possible outside of Vala or C/C++. To start pulling on that thread see the Gnome bugs [#694115](https://bugzilla.gnome.org/show_bug.cgi?id=694115) and [#639908](https://bugzilla.gnome.org/show_bug.cgi?id=639908). There is mention of using a Vala or C "shim" to get around this, but I'm not sure of the logistics of including something like that in an extension, nevermind how to implement one.

Gnome Contacts does offer a DBus interface that is used as a Search Provider for the shell, but it only offers contact avatars and names. Help with this issue in general would be greatly appreciated.

**Comment by andyholmes** [comment]
I've just filed [Bug #786187](https://bugzilla.gnome.org/show_bug.cgi?id=786187) in the Gnome bug tracker for gnome-contacts regarding this issue, although even if it were implemented today it wouldn't hit the desktop for some time.

**Comment by cwmke** [comment]
Thanks for the thorough breakdown and for filing the bug report. Hopefully some day in the future they create an easier way to access the data.

**Comment by andyholmes** [comment]
Just a quick update, Niels De Graef pointed me to @hugosenari's [folks](https://github.com/hugosenari/folks) shim he wrote in Python I'm investigating. If all goes well, I might get you test a build for me since I don't have any other providers in GOA myself.

**Comment by cwmke** [comment]
Sounds good. Let me know when you're ready for me to test it out.

**Comment by andyholmes** [comment]
@cwmke here is a build that includes preliminary support for using libfolks, which should pull in contacts from GOA, evolution and some other places. Be warned it includes many other changes including some possible bugs, but shouldn't be dangerous to your system in any way.

Let me know if this pulls in your contacts from NextCloud.

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1224177/mconnect.andyholmes.github.io.zip)

**Comment by hugosenari** [comment]
Hi, i'm glad to be cited here :smiley: 

To be honest I'm not happy with my solution because:
- it uses a redefinition of an static type (c struct),
- it point new object instance to actual memory address created by libfolks,
- if this redefinition [isn't equal to current version](https://stackoverflow.com/questions/8668333/create-python-object-from-memory-address-using-gi-repository), this code won't work.
- it is ugly :laughing:

But referenced glib bug was reported in [2011](https://bugzilla.gnome.org/show_bug.cgi?id=639908) and nobody solved it :disappointed: 

Recommended [discussion](https://github.com/kupferlauncher/kupfer/issues/39) it's why I made it, and maybe give you other options (ie. folks-inspect)

**Comment by cwmke** [comment]
It doesn't seem to pull them in although I'm in Fedora so SELinux might be messing with it. I'll try it in a VM later tonight and update this. Thanks!

**Comment by andyholmes** [comment]
@cwmke perhaps as an easier test, try running `folks-inspect individuals` (you may have to install it). I wasn't aware that hugo's code actually referenced in-memory adresses, could be you're right about SELinux. But if your contacts don't show in folks-inspect, chances are they won't anyways.

@hugosenari Yeah, this bug is gruesome :( I've run into it several times. According to Philip Whitnall (GData, Folks, Gnome-Contacts, etc) Libgee is basically dead, Vala is terminal and GI introspection is poorly maintained. On the bug I filed above there's much talk about removing Gee from Folks but it's a lot of work and there is no replacement for those container types. That's like 5 sad faces :(

**Comment by cwmke** [comment]
I just ran `folks-inspect individuals` on Fedora as well as Arch receiving a list of individuals on both. As for the contact options popping up while typing the name in for a text, Arch did not work and displayed no error. Fedora also didn't work while presenting the following error before displaying all of the individuals.

`````
folks-WARNING **: backend-store.vala:434: Error preparing Backend 'telepathy': The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files

**Comment by andyholmes** [comment]
@cwmke Arg. It seems like either you're right and SELinux is (rightly so) rejecting the attempt to access in memory addresses (the telepathy warning is likely indicating folks hasn't found the telepathy provider, not an issue) or worse Hugo is right and it's an issue with his "voodoo" bindings, in which case I have no idea. I basically just copy-pasted that stuff.

The main problem I've found with folks-inspect is the lack of detailed information, eg. no type for phone numbers, so it could pull in fax numbers with no way of notifying the user (unless they recognised the number).

I'll have a look at writing a custom mini folks-inspect in Vala, but I've never written any of that, so wish me luck. At v7 my extension is still not been reviewed on the extensions site, so at least I'm less worried about including non-GJS code in the extension.

**Comment by cwmke** [comment]
Thanks for taking a crack at this! Best of luck in your efforts. 😃

**Comment by hugosenari** [comment]
@cwmke can you please [change folks.py](https://gist.github.com/hugosenari/d13ca7274510e4dc6850b8b97537d096/revisions#diff-6e731233fcdf5c9b0f3bae4d1ba97241) put `print('folk: ', folk.get_id())` after 293 and run it with python to see if at least we are getting contacts?

**Comment by cwmke** [comment]
It shows a screen full of contacts (not all of them) and then exits with the below error. I tested with python 2 and 3 and had the same result. I'm not sure which is preferred here.

~~~
Traceback (most recent call last):
  File "folks.py", line 247, in _on_quiescent
    self.on_ready(self.aggregator)
  File "folks.py", line 300, in ready
    phone_number.parameters['type']
KeyError: 'type'

**Comment by andyholmes** [comment]
I believe this is Python3 (I usually just check if `print` is a statement, it's usually python2). That particular bit of code is my own, to retrieve the phone number type. Seems like maybe it does work after all, just not that one bit. Could you check if its the same as this file? This was the last revision I was using locally, may have fixed that, I remember having to abuse the GeeIterator @hugosenari wrote.

[folks.py.txt](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1230220/folks.py.txt)

**Comment by cwmke** [comment]
Same result. Do you want me to use the new release from today or the custom zip you had above (or does it not matter)?

**Comment by andyholmes** [comment]
Ah, I've actually stripped the folks part out, after you reported it not working the first time. If the file I just posted above is the same, lets have @hugosenari give it a look over, it's still mostly his code after all, so he may have a clue what I did wrong.

It worked me, but then I wrote it to work Google Contacts, just via folks instead of GData. Could be there are some differences, does NextCloud list phone number types? Perhaps it just choked on a number that didn't have one specified?

**Comment by hugosenari** [comment]
@cwmke this is really nice, you are getting contacts and some phone numbers but one of them has no 'type', causing this error, try [change](https://gist.github.com/hugosenari/d13ca7274510e4dc6850b8b97537d096/revisions#diff-6e731233fcdf5c9b0f3bae4d1ba97241) `phone_number.parameters['type']` by `phone_number.parameters.get('type', 'unknown')` this will try get _type_ from parameters, and if can't find it use _unknown_

**Comment by cwmke** [comment]
The ones that work all display `+xx xxx xxx xxxx (type)`. There is probably a funky one in there somewhere. I just ran through my contacts and cleaned them up a bit but same result. The debug message doesn't tell me which contact is creating the issue which makes it hard to correct. Any ideas how I can figure that out?

**Comment by cwmke** [comment]
Success! Thanks a lot for all of your help @hugosenari  and @andyholmes.

**Comment by andyholmes** [comment]
@cwmke that's good to hear, did it work with the new code or did you have to manually correct all your contacts? I'm hoping I can move to folks entirely so more people can access their contacts.

@hugosenari Thanks a lot for your help! I hope one day they fix that introspection bug

**Comment by cwmke** [comment]
It worked with the new code from this comment.

> try change phone_number.parameters['type'] by phone_number.parameters.get('type', 'unknown') this will try get type from parameters, and if can't find it use unknown

**Comment by andyholmes** [comment]
@cwmke Excellent, I'll keep the old code around but merge this as the default and see how it goes for everyone

**Comment by Queuecumber** [comment]
Hey just updated to the latest code and now I'm not getting any contact suggestions. Followed the instructions and installed gir folks, enabled debug mode and nothing unusual printed in the logs. Saw that you wanted issues reported on this bug. Let me know what you want me to try

**Comment by hugosenari** [comment]
Let's start again :confused:, @Queuecumber did you tested `folks-inspect individuals` to see if libfolks are reading your contacts?
If it are listing your contacts, can you please run this [folks.py](https://gist.githubusercontent.com/hugosenari/d13ca7274510e4dc6850b8b97537d096/raw/a4f8d0ee52a628a2426d9d31a9610251aa8e63da/folks) with python3 and say if is listing your contacts or you are getting any errors?

**Comment by andyholmes** [comment]
@Queuecumber thanks for reporting so soon! I put a note on the release warning users - I hope we can get to the bottom of this!

**Comment by cwmke** [comment]
I can confirm the latest update isn't working for Arch either (the one working yesterday). Fedora doesn't work even with yesterday's fix so I'm not sure what's causing that.

**Comment by andyholmes** [comment]
I just did a diff of what hugo has and what I uploaded, there shouldn't be any difference, except that hugo's won't work with sms.js, because it omits the display_name() call and includes a get_id() call.

**Comment by andyholmes** [comment]
:( Sorry, have been distracted by my pregnant cat, forgot to include folks.py in the ZIP!

Try this please: 
[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1233134/mconnect.andyholmes.github.io.zip)

**Comment by cwmke** [comment]
No trouble and those are some good looking kittens. The new one works on Arch. No luck with Fedora.

**Comment by Queuecumber** [comment]
Ok so I don't have the `folks-inspect` binary and I couldnt find an obvious way to install it. However, the `folks.py` provided did list a whole bunch of stuff which I assume is correct (phone numbers seem right, other than that it was ID numbers, no names, I assume thats expected).

Then I pulled the latest commits but I think that reverted folks (based on some commit messages) so my autocomplete is working again but I assume through GOA not through folks. I have a feeling it was just the missing `folks.py` that was causing my failure.

**Comment by Queuecumber** [comment]
And indeed when I `git checkout 8781f0e8e79536371d39732327d322768bd2de40` and rebuild, contact autocomplete works as  expected and the window is much snappier now since it can use async. So I think you are in good shape if you can fix the reported issue on Fedora, I'm of no help there (on Ubuntu)

**Comment by Queuecumber** [comment]
However, I can't  seem to actually send SMS to some people. I tested two contacts, one worked fine, the other caused the search bar the turn red when I tried to hit send. Not sure what the issue is and `gjs sms.js ...` didnt print any error messages

**Comment by andyholmes** [comment]
@Queuecumber I pulled the code which initialises folks.py in sms.js until I figure out how to handle errors with it. Here is a current build which attempts to use folks and check for errors:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1235479/mconnect.andyholmes.github.io.zip)

Even while explicitly calling a non-zero return code, GLib.spawn_async_with_pipes always seems to return success, so instead it checks for anything printed to stderr (sketchy).

@cwmke If you could try this on your SELinux box that would give me a clue if this can fail gracefully.

**Comment by andyholmes** [comment]
@Queuecumber in regards to the search bar turning red, the current matching/validating code is rather convoluted, and I've been meaning to revisit it, but haven't gotten around to it.

**Comment by andyholmes** [comment]
Okay, here's my final build for the night with folks support, falling back to GOA, with fixed validation and sending to contacts. Give it a good run through, if you please.

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1236048/mconnect.andyholmes.github.io.zip)

**Comment by cwmke** [comment]
Still nothing for Fedora. When I run either `folks-inspect individuals` or `python3 folks.py` I get the following error followed by the list of contacts in their proper form. I'll play around with telepathy but I'm not sure why that would be needed or causing issues. The fact that the list shows in the cli is a good sign though.

~~~
(folks-inspect:5928): folks-WARNING **: backend-store.vala:434: Error preparing Backend 'telepathy': The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files
~~~

**Comment by andyholmes** [comment]
It shouldn't be necessary, that's for sure. I think it really is just a warning telling you it's failed to pull in IM contacts. I can have look tomorrow at specifying not to look for that backend, it might be possible and telepathy contacts should be irrelevant, I doubt they ever carry phone numbers. If not, I may be able to filter that warning out and ignore it.

Could you tell me if sms.js will still open and/or fail gracefully to load folks contacts? Because of a weird bug with spawning folks.py I have it set to check stderr for any messages and fallback to GOA/GData, then no contacts (ie manual phone numbers only).

**Comment by cwmke** [comment]
The interface still pops up and is able to send texts with a number added directly if that's what you're looking for? I also checked journalctl's output and `gjs[2582]: JS LOG: Folks: error reading folks` shows. `python3 folks.py` returns the same error followed by a 5-10 second delay before displaying the list of contacts. Let me know if you're looking for something else.

**Comment by andyholmes** [comment]
@cwmke Nope, that's actually good news (sort of) because it means my error checking is working, it's just catching non-fatal errors. At least this time the SMS app is sill usable when folks fails. Try giving this one a quick shot, it's virtually the same but tries to ignore the telepathy error:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1236619/mconnect.andyholmes.github.io.zip)

**Comment by cwmke** [comment]
No change.

**Comment by andyholmes** [comment]
@cwmke could you run `python3 folks.py 2>error.txt` and upload that file so I know byte-for-byte what's being printed?

**Comment by cwmke** [comment]
`
(process:3613): folks-WARNING **: backend-store.vala:434: Error preparing Backend 'telepathy': The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files
`

**Comment by andyholmes** [comment]
I assume that's all on one line with no newline (\n) characters? Anyways, this one tries to read stderr until it's empty, ignoring empty lines and lines containing "WARNING":

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1236651/mconnect.andyholmes.github.io.zip)

Thanks for working through this with me, I know it's arduous

**Comment by cwmke** [comment]
Correct, all one line. I'll format it as such in the future. :-)
```
(process:4515): folks-WARNING **: backend-store.vala:434: Error preparing Backend 'telepathy': The name org.freedesktop.Telepathy.AccountManager was not provided by any .service files
```

No trouble at all! I'm happy to help. I think this is a very worthwhile extension as KDE-Connect is my favourite feature from KDE and I'd like to see a high quality equivalent for Gnome.

**Comment by andyholmes** [comment]
Nothing from that last one I posted?

**Comment by cwmke** [comment]
That last one is working! I still see the error but I'm able to see contacts.

**Comment by andyholmes** [comment]
Excellent! So SMS opens and you get your autocompletion? Is the little logo the "default avatar" symbolic icon?

**Comment by cwmke** [comment]
Yes, all of that is correct. The remaining issue is that the sms window is very slow to open each time. About the same wait as for fetching the contacts from the cli.

**Comment by andyholmes** [comment]
Right now it reads from stderr _synchronously_ to make sure we've checked all errors before proceeding to load contacts asynchronously. It might be unavoidable (google "javascript async exception" the gist of that nightmare), but I'll have look into it later today. Thanks for your help!

**Comment by andyholmes** [comment]
@cwmke Give this one a shot when you get a chance. I think I've found a way to disable the telepathy backend, and error checking should be asynchronous, too:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1236835/mconnect.andyholmes.github.io.zip)

**Comment by cwmke** [comment]
The SMS window pops up immediately which is definitely a nice improvement 😃. The same error still comes up though as well as a delay before names being listed.

**Comment by andyholmes** [comment]
Is the error only when you run `python3 folks.py` directly, but contacts work in the app? Basically sms.js now runs `FOLKS_BACKENDS_DISABLED=telepathy python3 folks.py`, but will still choke and fallback to GOA/Google if there's any other error.

**Comment by cwmke** [comment]
Correct, the error occurs when I run `python3 folks.py` directly. The contacts work in the app but they only appear after the same delay we find in the cli.

**Comment by andyholmes** [comment]
@cwmke Ah well, that's as good as it will get probably. I think folks might still do an online fetch each time it's called, but at least it's asynchronous now. I think it's finally ready for prime-time, thanks again for the help!

**Comment by cwmke** [comment]
Thanks for all your work on this. It's turned out very well!
