### ISSUE TITLE
Keyboard Shortcut For Panel Indicator

### ISSUE THREAD

**Issue by cwmke** [andyholmes/gnome-shell-extension-mconnect#26]
One of the things I wish Gnome had that KDE has is better keyboard access. Any chance of a keyboard shortcut to open and close the panel? Customizable is preferable. For an existing extension with this take a look at [Clipboard Indicator](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator).

**Comment by andyholmes** [comment]
Sure, I could probably do that. Lower priority, but I'll take a look when I can.

**Comment by andyholmes** [comment]
I've been putting some thought into this, but I'm not sure how exactly to pull this off. A couple issues have occured to me:

* There could obviously be more than one device, which would imply a sort of [Ctrl/Alt/etc]+1+[?/definable] style keybinding with automatically assigned numbers because...
* The extension doesn't really "manage" the devices so much as handle them, so there's no way to statically assign these numbers (ie. they could change with each reboot/session change/etc)

I'm really not a keyboard access person myself, so if you have at least "user experience" with how these things usually play out in programs or how keybinding conflicts are resolved, I'd be glad to hear about it.

**Comment by cwmke** [comment]
I think an extension would usually have some sort of customizable keybinding to open the info bubble similar to Meta+[a-z 0-9] or something similar. You raise a good point about the complication of multiple device indicators. I can think of 3 options off the top of my head.

1. Device Indicators = off. Single keybinding opens the expanded menu in the options menu in the upper right corner (no idea what the official name is 😅). I'm not sure if this is a simple or complicated matter but for my use case, this would remove the need for indicators at all as it provides a quick method to get to the battery percentage and the options.

2. As you mentioned Ctrl/Alt/Meta/Custom + [0-9]. I would be happy with this option as well. I haven't experienced any other extensions that have this sort of use case so I'm unsure of how difficult to implement this idea is.

3. My general goal with a keybinding is to quickly check information and select options without touching the mouse which would also work if the first indicator is the only one selected. That's a bit uglier solution but one I'd be happy with.

Option 1 is my favorite simply because it cleans up the interface a bit (no more indicators) and presents everything in one place. One of the reasons I used to jump from Gnome to KDE was due to KDE allowing me to add customizable keybindings to everything. Hopefully this extension can accomplish the same without a ridiculous amount of work for you. 🤞

**Comment by andyholmes** [comment]
With regard to:

1. I don't think that's too hard to do, I have the *Mobile Devices* menu marked as property I can grab easily and probably move the cursor there, too. Although, a number of people have stated they prefer the "in the menu" approach, I'd still like to keep the indicator-kdeconnect style around since some may still prefer or just be comfortable with it. I don't see that being impossible to juggle though.

2. I mean, it is possible to track them by device ID, just harder if the device changes ID's which may happen (I can't remember exactly how they're generated). If it does, it might just mean keeping a GSetting around to associate them with.

3. It's funny, because there's a default keybinding to open almost everything on the panel *except* the User Menu:
    * Applications => Super+A
    * App Menu => Super+F10
    * Calendar => Super+V
    * Popped-Up Notification => Super+N
    * Overview => Super+S

I think the biggest thing I'm worried about is overwriting current bindings, although if it's confgurable that's not really my fault anyways ;) I'll think about it some more, while I try to get some stuff in mconnect on the go (and I know less Vala than Javascript). Thanks for your input, as always.

**Comment by cwmke** [comment]
One thing I want to add to 2 is that I actually prefer the number to match the order shown not by device. Thanks for giving it so much attention. I wasn't expecting anything for quite awhile. 😄

**Comment by andyholmes** [comment]
So I've been looking more into this, it's actually pretty easy, but by the same token limited. Here's pretty much how it goes:

**Pros:**
* It's *really* simple to bind keys in Gnome Shell
* A function automatically binds a GSetting of an accelerator (eg. \<Shift\>\<Alt\>1) to a callback function.
* The callback function can basically do anything (eg open menus, set keyboard focus, activate buttons, etc)

**Cons:**
* I don't think it's possible to add a GSettings key dynamically, which means a predetermined, fixed amount of devices with keybindings *or* just one device which could be set as a default.
* It doesn't seem possible to chain a modifier and two keys (eg. \<Alt\>\<Shift\>1+S for "Send SMS" with Device One), which makes the "default" style seem a little more appealing
* Another reason to find that appealing is that although the devices in the User Menu are added top to bottom, for some reason the indicators are added right-to-left, and I'm not sure if I can change that since it's a Gnome Shell function, not one of the extension's. That might make "the order shown" as you describe it not what it appears to be and difficult to balance with the "properly-ordered" User Menu devices.
* There aren't actually that many unused, *easy* keybindings free! Since it only makes sense to make this available globally, it could easily conflict with Google Chrome, Firefox or any other keybinding heavy application. I need to do some testing to see if those are even "overwritable" by Gnome Shell, of if they'll both become active.
* Navigating the buttons in a device menu seems flaky and/or awkward, which may be my fault, but I'm not sure.
  * Up, down and right arrow keys work as expected, but left arrow closes whichever menu or sub-menu you're currently in, regardless of what's focused in said menu.
  * The left-most focusable button in the device menu seems to be the second item (eg. "Locate device", not "Send SMS" as it should be). In the case of an unpaired device, the pair button doesn't seem to accept keyboard focus at all :(
  * The first focused button after pressing up or down is actually the second *focusable* item, and because of the above point this is "Browse device".

I'll leave it at that for now, while I continue investigating, but any thoughts you have are welcome as always.

**Comment by andyholmes** [comment]
@cwmke A quick teaser ;)

![screenshot from 2017-09-03 14-50-23](https://user-images.githubusercontent.com/1265208/30006859-442d7998-90b7-11e7-8700-28a43f12e6a8.png)

**Comment by cwmke** [comment]
Looks great! Sorry for the delay. I just saw this. So these are customizable?

**Comment by andyholmes** [comment]
Yep, it actually turned out to be a very interesting challenge. The *Extension* shortcuts were easy, but the *Device* ones were tricky.

By default all keybindings are unbound, to avoid conflicts with current keybindings (there's actually a obscure corner case I can't really fix, but this should ensure it's almost impossible to trigger). You can set them one by one, per device and the extension will overwrite it's own bindings if necessary, and refuse to set a binding that another program has grabbed. I've found the \<Ctrl\>+\<Super\>+? chain of shortcuts have the largest amount of unused bindings, so that's what I use.

Here's a test build which is 95% what v13 will be, I just have to settle on some aesthetics, a few translatable strings and fix the *Browse Files* shortcut, which is a bit tricky. But you could safely use this one until I release v13 if you wanted to test:

[mconnect@andyholmes.github.io.zip](https://github.com/andyholmes/gnome-shell-extension-mconnect/files/1275692/mconnect.andyholmes.github.io.zip)

**Comment by andyholmes** [comment]
Marking this closed, since it all seems to work for me.

**Comment by cwmke** [comment]
Working for me too. Thanks!
