### ISSUE TITLE
"Search devices" state does not sync

### ISSUE THREAD

**Issue by rugk** [andyholmes/gnome-shell-extension-mconnect#31]
STR:
1. In the menu select "Search for devices"
2. Now go to a (disconnected) phone indicator.

You see: A button allowing to search for devices, although the search is already running.
You should see: "Searching for devices."

v11
Fedora 26

**Comment by andyholmes** [comment]
It's possible, I'll have to put some thought into it, though. Even though both scans technically do the same thing, they're used for different purposes, so the best fix may be to use different language; "Re-connecting to device" -> "Discover new devices". Here's the full run-down:

In KDE Connect each request to discover devices gets a unique Id which needs to be released (somehow) or it will scan forever. When the KDE Connect settings panel is opened, for example, it requests a discovery for the precoess id (PID) of the settings panel, and releases it when the panel is closed. I can't remember what MConnect does since it doesn't expose this on the DBus interface anyways (yet).

In the extension there are two types of requests:
  * when "Scan for devices" is selected in the User Menu, it opens a request for "manager" which can only be stopped by selecting "Stop scanning for devices" in the User Menu. This type of scan is really meant for _discovering_ unknown/unpaired devices.
  * when the "Scan for device" button is selected in a device menu, a request is opened for Id of that device and can be released by clicking the button again or automatically releases when that device re-connects. This type of scan is really meant for _re-connecting_ to a known/paired device.

Both of these initiate the same type of "global scan", just with different Id's that are tracked by the backend code (`kdeconnect.js`/`mconnect.js`) since KDE Connect doesn't expose a list of the current requests, only whether scanning is in progress. Making these two scans interact with each other would result in situations where toggling either type of scan would either overwrite the other request, or would seem to be unresponsive/do nothing.

**Comment by rugk** [comment]
> In KDE Connect each request to discover devices gets a unique Id which needs to be released (somehow) or it will scan forever. 

Good point, I saw another difference: The menu scan will really scan forever, this may be quite unexpected. The indicator scan seems to automatically stop after a while.
(just saw you wrote this below, too, still is not an "scan forever" a battery drain or so? Compare it to Bluetooth: There it also does not scan forever.)

**Comment by andyholmes** [comment]
As far as I know "reconnecting" to a device should also scan forever, unless KDE Connect has an internal timeout I didn't notice. I'll look into adding a timeout to the local code if it doesn't.

**Comment by andyholmes** [comment]
It seems although the KDE Connect settings panel calls acquireDiscoveryMode() and doesn't call releaseDiscoveryMode() until it's closed, kdeconnect-cli on the other hand only keeps the discovery mode open for a period of two seconds before releasing. Given that I may just drop the persistent scan entirely and do it like kdeconnnect-cli, which would be a lot less complex that what I'm doing now.
